fix: enforce Patients to have unique primary hospital identifier
dot-base/fhir-server pull request #113
Opened 2021-12-14 10:08 UTC by andreakreichgauer

This introduces checking for duplicate patient primary identifiers before a patient resource is created. This closes #112 .

2021-12-17 11:25 UTC, rti reviewed
Sorry, I cannot get it to work. I can still repeatedly execute the follwoing and create lots of maxes... Shouldn't it fail due to `patient-dotbase-identifier` and `patient-primary-identifier` being the same?

```
POST http://localhost:8080/api/fhir/Patient
Content-Type: application/json

{
  "resourceType": "Patient",
    "identifier": [
    {
      "use": "usual",
      "type": {
        "coding": [
        {
          "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
          "code": "MR"
        }
        ]
      },
      "system": "https://dotbase.org/fhir/NamingSystem/patient-primary-identifier",
      "value": "622288230",
      "assigner": {
        "identifier": {
          "system": "http://fhir.de/sid/arge-ik/iknr",
          "value": "261101015"
        },
        "display": "Charité – Universitätsmedizin Berlin"
      }
    },
    {
      "use": "usual",
      "type": {
        "coding": [
        {
          "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
          "code": "PI"
        }
        ]
      },
      "system": "https://dotbase.org/fhir/NamingSystem/patient-dotbase-identifier",
      "value": "4739130169",
      "assigner": {
        "display": "dot.base"
      }
    },
    {
      "use": "official",
      "type": {
        "coding": [
        {
          "system": "http://fhir.de/CodeSystem/identifier-type-de-basis",
          "code": "GKV"
        }
        ]
      },
      "system": "http://fhir.de/sid/gkv/kvid-10",
      "value": "92010150M335",
      "assigner": {
        "identifier": {
          "use": "official",
          "system": "http://fhir.de/sid/arge-ik/iknr",
          "value": "260326822"
        }
      }
    }
  ],
  "active": true,
  "name": [
  {
    "use": "usual",
    "family": "Mustermann",
    "given": [
      "Max"
    ]
  }
  ],
  "telecom": [
  {
    "system": "phone",
    "value": "0123456789",
    "use": "mobile"
  },
  {
    "system": "email",
    "value": "max@temporary-mail.net",
    "use": "home"
  }
  ],
  "gender": "male",
  "birthDate": "1950-01-01",
  "deceasedBoolean": false,
  "address": [
  {
    "use": "home",
    "line": [
      "Musterstrasse 1"
    ],
    "city": "Musterstadt",
    "postalCode": "01234",
    "country": "DE"
  }
  ]
}
```

2021-12-20 10:40 UTC, andreakreichgauer commented on src/main/java/ca/uhn/fhir/jpa/starter/JpaRestfulServer.java
> +      registerInterceptor(patientCreateInterceptor);
The issue here is, that both interceptors hook at the same pointcut - before a new patient is written to the database. But duplicate-checks should always happen before registering a new patient at keycloak.

That's why both is handled in the same interceptor, if patientRegistration is enabled, to enforce it's executed in the correct order. If patientRegistration is disabled patientCreateInterceptor handles duplicate checking only.

But I think this definitely is lacking some comment here, to explain why it's inside if-else ;)

2021-12-20 10:40 UTC, andreakreichgauer commented on src/main/java/ca/uhn/fhir/jpa/starter/dotbase/services/PatientCreate.java
> +    if (patientIdentifier == null) {
Yes, not existing identifiers should pass. Since it is not required for patients to have those identifier. Just if they have one, there shouldn't be duplicates

2021-12-20 10:40 UTC, andreakreichgauer commented on src/main/java/ca/uhn/fhir/jpa/starter/dotbase/services/PatientCreate.java
> +    if (hasDuplicate) {
The oppostie would'nt be correct, since it can be `hasDuplicate:false` or `hasDuplicate:true` depending on the duplicates found and the resulting value of `duplicates.isEmpty()`.
But I see your point that the naming is somehow not intuitive, I just couldn't find anything better.

2021-12-20 12:00 UTC, rti requested changes

2021-12-20 12:00 UTC, rti commented on src/main/java/ca/uhn/fhir/jpa/starter/dotbase/services/PatientCreate.java
> +    if (hasDuplicate) {
Please push the commit containing the missing `!` we talked about.

2021-12-20 12:13 UTC, andreakreichgauer commented on src/main/java/ca/uhn/fhir/jpa/starter/dotbase/services/PatientCreate.java
> +    if (hasDuplicate) {
yes, it was on the next pr branch ;) it's pushed now

2021-12-20 12:13 UTC, rti requested changes
```
POST http://localhost:8080/api/fhir/Patient
Content-Type: application/json

{
  "resourceType": "Patient",
    "identifier": [
    {
      "use": "usual",
      "type": {
        "coding": [
        {
          "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
          "code": "MR"
        }
        ]
      },
      "system": "https://dotbase.org/fhir/NamingSystem/patient-primary-identifier",
      "value": "633389362",
      "assigner": {
        "identifier": {
          "system": "http://fhir.de/sid/arge-ik/iknr",
          "value": "261101015"
        },
        "display": "Charité – Universitätsmedizin Berlin"
      }
    },
    {
      "use": "usual",
      "type": {
        "coding": [
        {
          "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
          "code": "PI"
        }
        ]
      },
      "system": "https://dotbase.org/fhir/NamingSystem/patient-dotbase-identifier",
      "value": "6770377332",
      "assigner": {
        "display": "dot.base"
      }
    },
    {
      "use": "official",
      "type": {
        "coding": [
        {
          "system": "http://fhir.de/CodeSystem/identifier-type-de-basis",
          "code": "GKV"
        }
        ]
      },
      "system": "http://fhir.de/sid/gkv/kvid-10",
      "value": "38161082T153",
      "assigner": {
        "identifier": {
          "use": "official",
          "system": "http://fhir.de/sid/arge-ik/iknr",
          "value": "260326822"
        }
      }
    }
  ],
  "active": true,
  "name": [
  {
    "use": "usual",
    "family": "Demassiado",
    "given": [
      "Gente"
    ]
  }
  ],
  "gender": "male",
  "deceasedBoolean": false
}
```

now returns an
```
POST http://localhost:8080/api/fhir/Patient

HTTP/1.1 500 Internal Server Error
Date: Mon, 20 Dec 2021 12:11:21 GMT
X-Powered-By: HAPI FHIR 5.4.1 REST Server (FHIR Server; FHIR 4.0.1/R4)
X-Request-ID: OS2KkeXbWuJE61Z0
Content-Type: application/fhir+json;charset=utf-8
Transfer-Encoding: chunked
Server: Jetty(9.4.42.v20210604)

{
  "resourceType": "OperationOutcome",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">ERROR</td><td>[]</td><td><pre>Failed to call access method: ca.uhn.fhir.context.ConfigurationException: Attempt to request all resources from an asynchronous search result.  The SearchParameterMap for this search probably should have been synchronous.</pre></td>\n\t\t\t</tr>\n\t\t</table>\n\t</div>"
  },
  "issue": [
    {
      "severity": "error",
      "code": "processing",
      "diagnostics": "Failed to call access method: ca.uhn.fhir.context.ConfigurationException: Attempt to request all resources from an asynchronous search result.  The SearchParameterMap for this search probably should have been synchronous."
    }
  ]
}
```

2021-12-20 12:40 UTC, rti commented
> ```
> POST http://localhost:8080/api/fhir/Patient
> Content-Type: application/json
> 
> {
>   "resourceType": "Patient",
>     "identifier": [
>     {
>       "use": "usual",
>       "type": {
>         "coding": [
>         {
>           "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
>           "code": "MR"
>         }
>         ]
>       },
>       "system": "https://dotbase.org/fhir/NamingSystem/patient-primary-identifier",
>       "value": "633389362",
>       "assigner": {
>         "identifier": {
>           "system": "http://fhir.de/sid/arge-ik/iknr",
>           "value": "261101015"
>         },
>         "display": "Charité – Universitätsmedizin Berlin"
>       }
>     },
>     {
>       "use": "usual",
>       "type": {
>         "coding": [
>         {
>           "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
>           "code": "PI"
>         }
>         ]
>       },
>       "system": "https://dotbase.org/fhir/NamingSystem/patient-dotbase-identifier",
>       "value": "6770377332",
>       "assigner": {
>         "display": "dot.base"
>       }
>     },
>     {
>       "use": "official",
>       "type": {
>         "coding": [
>         {
>           "system": "http://fhir.de/CodeSystem/identifier-type-de-basis",
>           "code": "GKV"
>         }
>         ]
>       },
>       "system": "http://fhir.de/sid/gkv/kvid-10",
>       "value": "38161082T153",
>       "assigner": {
>         "identifier": {
>           "use": "official",
>           "system": "http://fhir.de/sid/arge-ik/iknr",
>           "value": "260326822"
>         }
>       }
>     }
>   ],
>   "active": true,
>   "name": [
>   {
>     "use": "usual",
>     "family": "Demassiado",
>     "given": [
>       "Gente"
>     ]
>   }
>   ],
>   "gender": "male",
>   "deceasedBoolean": false
> }
> ```
> 
> now returns an
> 
> ```
> POST http://localhost:8080/api/fhir/Patient
> 
> HTTP/1.1 500 Internal Server Error
> Date: Mon, 20 Dec 2021 12:11:21 GMT
> X-Powered-By: HAPI FHIR 5.4.1 REST Server (FHIR Server; FHIR 4.0.1/R4)
> X-Request-ID: OS2KkeXbWuJE61Z0
> Content-Type: application/fhir+json;charset=utf-8
> Transfer-Encoding: chunked
> Server: Jetty(9.4.42.v20210604)
> 
> {
>   "resourceType": "OperationOutcome",
>   "text": {
>     "status": "generated",
>     "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">ERROR</td><td>[]</td><td><pre>Failed to call access method: ca.uhn.fhir.context.ConfigurationException: Attempt to request all resources from an asynchronous search result.  The SearchParameterMap for this search probably should have been synchronous.</pre></td>\n\t\t\t</tr>\n\t\t</table>\n\t</div>"
>   },
>   "issue": [
>     {
>       "severity": "error",
>       "code": "processing",
>       "diagnostics": "Failed to call access method: ca.uhn.fhir.context.ConfigurationException: Attempt to request all resources from an asynchronous search result.  The SearchParameterMap for this search probably should have been synchronous."
>     }
>   ]
> }
> ```

Caused by: ca.uhn.fhir.context.ConfigurationException: Attempt to request all resources from an asynchronous search result.  The SearchParameterMap for this search probably should have been synchronous.
	at ca.uhn.fhir.rest.api.server.IBundleProvider.getAllResources(IBundleProvider.java:130)
	at ca.uhn.fhir.jpa.starter.dotbase.services.PatientCreate.hasDuplicate(PatientCreate.java:58)
	at ca.uhn.fhir.jpa.starter.dotbase.services.PatientCreate.checkDuplicate(PatientCreate.java:45)
	at ca.uhn.fhir.jpa.starter.dotbase.services.PatientCreate.checkDuplicates(PatientCreate.java:35)

2021-12-20 13:10 UTC, rti approved these changes

2021-12-20 13:13 UTC, merged