fix: error message on PatientRegistration failure
dot-base/fhir-server pull request #141
Opened 2022-04-12 15:25 UTC by rti

closes #140
The actual error was caused by the FHIR server trying to recreate patients on keycloak which were already created. So the behavior is as expected and should not be changed. This change improves the error message in order to guide our future selves.

2022-04-13 09:27 UTC, friedow requested changes

2022-04-13 09:27 UTC, friedow commented on src/main/java/ca/uhn/fhir/jpa/starter/dotbase/services/PatientRegistration.java
> +  // private static final org.slf4j.Logger ourLog = org.slf4j.LoggerFactory.getLogger(PatientRegistration.class);
There is some dead comment left ;)

2022-05-10 07:44 UTC, friedow approved these changes

2022-05-17 08:43 UTC, andreakreichgauer approved these changes

2022-05-17 08:45 UTC, merged