feat: add authorization rules for patient user
dot-base/fhir-server pull request #168
Opened 2022-09-29 18:26 UTC by andreakreichgauer

This introduces/fixes/improves feature/bug/enhancement description. This closes #1337.

BREAKING CHANGE: some breaking change description or DELETE this line.

2022-10-17 07:46 UTC, rti requested changes

2022-10-17 07:46 UTC, rti commented on src/main/java/ca/uhn/fhir/jpa/starter/dotbase/interceptor/authorization/UserRoleInterceptor.java
> +      this.uuid = "";
Could we set `uuid` to NULL as well? So we do not need to do string compare later on.

2022-10-17 07:46 UTC, rti commented on src/main/java/ca/uhn/fhir/jpa/starter/dotbase/interceptor/authorization/UserRoleInterceptor.java
> +      ruleBuilder = userSpecificRules(patientUser);
The rule builder is overwritten here, is this intended?

2022-10-17 07:46 UTC, rti commented on src/main/java/ca/uhn/fhir/jpa/starter/dotbase/interceptor/authorization/UserRoleInterceptor.java
> +    ruleBuilder.allow("ALLOW_TRANSACTIONS").transaction().withAnyOperation().andApplyNormalRules().andThen();
Do we really allow those things when there is no uuid?

2022-10-17 07:46 UTC, rti commented on src/main/java/ca/uhn/fhir/jpa/starter/dotbase/services/Authentication.java
> +    String userrealm = AuthTokenUtils.getUsername(jwtClaims);
shouldn't that be `getRealm`?

2022-10-17 07:46 UTC, rti commented on src/main/java/ca/uhn/fhir/jpa/starter/dotbase/interceptor/authorization/UserRoleInterceptor.java
> +      ruleBuilder.allow("ALLOW_POST_ON" + resourceType + "_IN_OWN_COMPARTMENT").create().resourcesOfType(resourceType)
How are those strings structured and where is this documented? Could you provide a pointer please?

2022-10-19 09:16 UTC, andreakreichgauer commented on src/main/java/ca/uhn/fhir/jpa/starter/dotbase/interceptor/authorization/UserRoleInterceptor.java
> +    ruleBuilder.allow("ALLOW_TRANSACTIONS").transaction().withAnyOperation().andApplyNormalRules().andThen();
This only enables transactions for allowed requests. In our case here this covers only GET on PlanDefinition, Questionnaire, ValueSet and CodeSystem

2022-10-19 09:19 UTC, andreakreichgauer commented on src/main/java/ca/uhn/fhir/jpa/starter/dotbase/interceptor/authorization/UserRoleInterceptor.java
> +      ruleBuilder.allow("ALLOW_POST_ON" + resourceType + "_IN_OWN_COMPARTMENT").create().resourcesOfType(resourceType)
These String are just custom names for the authorization rules. In case a request return 401 they appear in the response message.
But anyhow, if they are not easy to understand let's overwork them or remove them I think ;) Maybe a technical documentation of our authorization rules is what makes more sense here

2022-10-19 09:24 UTC, andreakreichgauer commented on src/main/java/ca/uhn/fhir/jpa/starter/dotbase/interceptor/authorization/UserRoleInterceptor.java
> +      ruleBuilder = userSpecificRules(patientUser);
Yes, it is overwritten to add patient specific rules. But I think restructuring the rules here might make more sense: the "not-user-specific-rules" could be removed here I think and might be something everyone is allowed to do.
Let's have a look at this together again

2022-10-19 13:00 UTC, andreakreichgauer commented on src/main/java/ca/uhn/fhir/jpa/starter/dotbase/interceptor/authorization/UserRoleInterceptor.java
> +      ruleBuilder.allow("ALLOW_POST_ON" + resourceType + "_IN_OWN_COMPARTMENT").create().resourcesOfType(resourceType)
I opened #179

2022-10-20 13:34 UTC, rti reviewed
WIP https://github.com/dot-base/end-to-end-tests/issues/9

2022-10-20 14:48 UTC, andreakreichgauer commented on src/main/java/ca/uhn/fhir/jpa/starter/dotbase/interceptor/authorization/UserRoleEnum.java
> +  //TODO: refactor setting adminUserName as env var. Use admin user from keycloak master realm instead?
I think the comment might be a bit misambogous. I meant that we should "refactor" it in terms of probably remove it and set the admin user via keycloak

2022-10-20 15:00 UTC, andreakreichgauer commented on src/main/java/ca/uhn/fhir/jpa/starter/dotbase/interceptor/authorization/UserRoleInterceptor.java
> +      "$meta-delete" };
I think this should be part of #177. I would suggest to make the medical user rules "deny-all-except-explicit-allows" as we did for the patient rules. But anyway we need to rework them with #177

2022-10-20 15:07 UTC, andreakreichgauer commented on src/main/java/ca/uhn/fhir/jpa/starter/dotbase/interceptor/authorization/UserRoleInterceptor.java
> +class AllUser {
:ok_hand:

2022-10-21 06:45 UTC, friedow commented on src/main/java/ca/uhn/fhir/jpa/starter/dotbase/interceptor/authorization/UserRoleInterceptor.java
> +      "$meta-delete" };
I've copied @rti 's comment to #177.

2022-10-21 07:36 UTC, friedow commented on src/main/java/ca/uhn/fhir/jpa/starter/dotbase/interceptor/authorization/UserRoleInterceptor.java
> +class AllUser {
I don't understand how this file is still used. Shouldn't all requests be handled by the `UserRoleInterceptor` anyway?

2022-10-21 07:36 UTC, friedow commented on src/main/java/ca/uhn/fhir/jpa/starter/dotbase/interceptor/authorization/AppAuthorizationInterceptor.java
> + */
I don't understand how this file is still used. Shouldn't all requests be handled by the UserRoleInterceptor anyway?

2022-10-21 07:38 UTC, friedow commented on src/main/java/ca/uhn/fhir/jpa/starter/dotbase/interceptor/authorization/UserRoleInterceptor.java
> +class AllUser {
I think you misunderstood the comment above. Let's talk about this :).

2022-11-03 10:48 UTC, rti commented on src/main/java/ca/uhn/fhir/jpa/starter/dotbase/interceptor/authorization/AppAuthorizationInterceptor.java
> + */
Will stay until Study FHIR Server is shut down. It is disabled by default via settings and only used on the Study FHIR Server.

2022-11-07 16:26 UTC, rti approved these changes

2022-11-07 16:28 UTC, merged