Feature/resolve external patient reference
dot-base/fhir-server pull request #22
Opened 2021-02-22 13:27 UTC by andreakreichgauer

---
🚀 Resolve external references for _include search
---

This resolves #21 

### 🚀 Description

Due to using separate FHIR servers for clinical,study and core data in dot.base, external references should be resolved and
returned as well.

 In general this aspect is handled by the `fhir-reverse-proxy` that handles all incoming resources - but only for simple requests like `.../fhir/Patient` or transaction bundles

Requests with `_include` params that result in a external reference to be included in the response, are covered by this PR.
 
### 🧰 Technical Solution
[What did you add / change to create this feature?]
- [ ] Extend `SearchBuilder` for custom behavior of `loadIncludes`
- [ ] Adapt SQL Query on `loadIncludes` to also include `targetResourceUrl`, which states external references
- [ ] add a `responseInterceptor` that fetches external resources and adds them to the outgoing response

2021-02-25 08:30 UTC, friedow requested changes

2021-02-25 08:30 UTC, friedow commented on src/main/java/ca/uhn/fhir/jpa/starter/dotBase/ResponseInterceptorExternalReference.java
> +    String resource = FhirServer.getExternalResource(url);
`FhirServer.getExternalResource` will work in development mode but it wont in production. At least not out of the box, since the url will be something like `https://dotbaseinstance.com/api/fhir/Patient/3`. Any request to this url will have to pass the authentication gateway. 

There are three possible solutions to this:
1. A custom entry in the /etc/hosts file to map from the external to the internal server address and bypass authentification between servers
2. Adding service users

What do you think @andreakreichgauer ?

2021-02-25 08:30 UTC, friedow commented on src/main/java/ca/uhn/fhir/jpa/starter/dotBase/ResponseInterceptorExternalReference.java
> +    return (resource == null ? null : parseToPatient(resource));
This function will automatically assume that if an external reference can be resolved the external resource has to be a Patient resource. Furthermore `parseToPatient` will throw an error if that is not the case. Is this intended?

2021-02-25 08:30 UTC, friedow commented on src/main/java/ca/uhn/fhir/jpa/starter/dotBase/searchBuilder/Queries.java
> +    ); else return Queries.NoTargetResourceType(findFieldName, searchFieldName);
Please use curly brackets to enclose return blocks instead of chaining this if statement.
```suggestion
    if (targetResourceType != null) {
        return Queries.withTargetResourceType(findFieldName, searchFieldName); 
    } else if (haveTargetTypesDefinedByParam) {
        return Queries.haveTargetTypesDefinedByParam(findFieldName, searchFieldName); 
    } else {
        return Queries.NoTargetResourceType(findFieldName, searchFieldName);
    }
```

2021-02-25 12:54 UTC, andreakreichgauer commented on src/main/java/ca/uhn/fhir/jpa/starter/dotBase/ResponseInterceptorExternalReference.java
> +    String resource = FhirServer.getExternalResource(url);
good point!
But both solutions would bypass authorization rules, if we might have patients, that not everybody is allowed to see.

Accordingly, I would suggest to just use the requester's auth token - you can get it from `theRequestDetails`. I added this to `FhirServer.getExternalResource`

2021-02-25 13:03 UTC, andreakreichgauer commented on src/main/java/ca/uhn/fhir/jpa/starter/dotBase/ResponseInterceptorExternalReference.java
> +    return (resource == null ? null : parseToPatient(resource));
Yes, I thought about it as well and was not sure, if we should allow all types of external resources to be resolved or narrow it to our use case of patients only -  all other resources would currently just be ignored for the response
-> see error handling below

Anyways, I changed it to all types of r4 resources now, since I don't see a point why not - what do you think?

About the error handling: if `parseToPatient` throws an error, it's currently already caught and handled by returning null. So the resource just won't be included in the response, if it can not be parsed to a valid FHIR r4 resource.
Or did you mean something else here?

2021-02-25 13:04 UTC, andreakreichgauer commented on src/main/java/ca/uhn/fhir/jpa/starter/dotBase/searchBuilder/Queries.java
> +    ); else return Queries.NoTargetResourceType(findFieldName, searchFieldName);
:+1:

2021-02-26 07:45 UTC, friedow commented on src/main/java/ca/uhn/fhir/jpa/starter/dotBase/ResponseInterceptorExternalReference.java
> +    return (resource == null ? null : parseToPatient(resource));
I don't see any problems in changing that to all resources either. :)

2021-02-26 07:45 UTC, friedow commented on src/main/java/ca/uhn/fhir/jpa/starter/dotBase/ResponseInterceptorExternalReference.java
> +    String resource = FhirServer.getExternalResource(url);
Nice solution :)

2021-02-26 07:47 UTC, friedow approved these changes
Nice 👍

2021-02-26 12:40 UTC, merged