authentication - verify and decode jwt
dot-base/fhir-server pull request #27
Opened 2021-03-31 14:48 UTC by andreakreichgauer

---
🚀 Authentication
---

This PR introduces authentication interceptor for incoming requests

### 🧰 Technical Solution
[What did you add / change to create this feature?]
- [ ] verify Bearer token from Authentication Header
- [ ] decode Beare token to jwt
- [ ] add `authentication_interceptor.enabled` to hapi.properties

### ‼ Known Issues
To test this feature locally `authentication_interceptor.enabled must be set to true and a valid public key for `idp_realm_public_key=` must be provided in hapi.properties

2021-04-01 07:30 UTC, friedow approved these changes
How do I get the public key of a keycloak realm?

2021-04-14 06:38 UTC, friedow requested changes

2021-04-14 06:38 UTC, friedow commented on src/main/java/ca/uhn/fhir/jpa/starter/HapiProperties.java
> +  public static String getRealmPublicKey() {
Is there any way we can determine the public key of a realm before starting the keycloak server itself? If not, we've got a deployment problem here. 

To set `IDENTITY_PROVIDER_REALM_PUBLIC_KEY` we need to have a running keycloak instance. The problem is, all services start at the same time. We would have to manually get the realm public key from `<your-sso-url>/auth/realms/<realm-name>` and set it on the fhir server as an env variable after the service has already started. This forces the service to restart.

I see two options to resolve this problem:
1. Retrieve the public key automatically from the keycloak server. I'd set an environment variable like `KEYCLOAK_URL`.
2. Use a key that can be determined before the keycloak server starts. This way we could set this on the inital stack launch.

2021-04-14 06:38 UTC, friedow commented on src/main/java/ca/uhn/fhir/jpa/starter/HapiProperties.java
> +    return HapiProperties.getBooleanProperty(AUTHENTICATION_ENABLED, false);
Since this a security feature, I think it should be enabled by default.

2021-04-23 16:40 UTC, andreakreichgauer commented on src/main/java/ca/uhn/fhir/jpa/starter/HapiProperties.java
> +  public static String getRealmPublicKey() {
Yes, that makes sense for the deployment. I changed it to option 1. The Public Key is retrieved from Keycloak once the fhir server comes up

2021-04-27 12:43 UTC, friedow submitted a review, later dismissed

2021-04-27 12:43 UTC, friedow commented on src/main/java/ca/uhn/fhir/jpa/starter/dotBase/api/IdentityProvider.java
> +      ourLog.info(e.getMessage());
Is this intentionally an `.info` call or did you mean to call `.error` here?

2021-04-27 12:46 UTC, friedow approved these changes

2021-04-27 12:52 UTC, andreakreichgauer commented on src/main/java/ca/uhn/fhir/jpa/starter/dotBase/api/IdentityProvider.java
> +      ourLog.info(e.getMessage());
good point. This should be ourLog.error

2021-04-27 12:53 UTC, merged