Feature - Secure endpoints for admin access only
dot-base/fhir-server pull request #54
Opened 2021-06-13 22:55 UTC by defo10

### 🚀 Feature Description
This PR introduces secure endpoints for admin access only. This resolves #43.

As I've found only three endpoints to secure, I opted for a blacklist authorization, i.e. normal users may do everything _but_ the denied operations. This seemed favorable compared to the alternative where i would basically need to allow all endpoints manually, something like below: 

```
IAuthRuleBuilder authNormalUserRules = new RuleBuilder()
            .allow().read().allResources().withAnyId().andThen()
            .allow().create().allResources().withAnyId().andThen()
            .allow().createConditional().allResources().andThen()
            .allow().write().allResources().withAnyId().andThen()
            .allow().delete().allResources().withAnyId().andThen()
            .allow().deleteConditional().allResources().andThen()
            .allow().patch().allRequests().andThen()
            .allow().graphQL().any().andThen()
            .allow().metadata().andThen();
            // + all (!) operations that are permitted but not the three forbidden ones
	    // + allow transactions
```

### 🧰 Technical Solution
- [x] Add AuthenticationInterceptor
- [x] Register AuthenticationInterceptor in JpaRestfulServer.java

#### 🧯 Minor other bugfixes
- [x] Close inputstream in DotbaseProperties.java
- [x] Throw 'no authentication' error if x-forwarded-user is set to empty String ""

2021-06-15 07:13 UTC, friedow requested changes

2021-06-15 07:13 UTC, friedow commented on src/main/java/ca/uhn/fhir/jpa/starter/dotBase/interceptors/AuthenticationInterceptor.java
> +    if (xForwardedUser != null && !xForwardedUser.equals("")) {
Replace nested conditionals with a [guard clauses](https://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html).

2021-06-15 07:13 UTC, friedow commented on src/main/java/ca/uhn/fhir/jpa/starter/dotBase/interceptors/AuthenticationInterceptor.java
>        return theRequestDetails.getHeader("X-Forwarded-User");
Return the already retrieved value instead of reusing the getter.
```suggestion
      return xForwardedUser;
```

2021-06-15 07:13 UTC, friedow commented on src/main/resources/dotbase.properties
> +Dotbase.AdminUserName=test-admin
Do not define a default for this property, because it reveals a potential attack vector for all servers that do not set this explicitly. The admin username should always be set explicitly.

2021-06-17 15:25 UTC, andreakreichgauer commented on src/main/java/ca/uhn/fhir/jpa/starter/dotBase/interceptors/UserAuthorizationInterceptor.java
> +    .build();
```suggestion
  private static final List<IAuthRule> USER_RULES = getUserRules();

  private static List<IAuthRule> getUserRules() {
    RuleBuilder ruleBuilder = new RuleBuilder();
    for (String endpoint : RESTRICTED_ENDPOINTS)
      ruleBuilder.deny("Restricted Endpoint or Operation - " + endpoint).operation().named("$logs").atAnyLevel()
          .andAllowAllResponses();
    return ruleBuilder.allowAll().build();
  }
```

2021-06-17 15:26 UTC, andreakreichgauer commented on src/main/java/ca/uhn/fhir/jpa/starter/dotBase/interceptors/UserAuthorizationInterceptor.java
> +  private static final List<IAuthRule> ADMIN_RULES = new RuleBuilder().allowAll().build();
```suggestion
  private static final String[] RESTRICTED_ENDPOINTS = {"$logs", "$mark-all-resources-for-reindexing", "$meta-delete"}
  private static final List<IAuthRule> ADMIN_RULES = new RuleBuilder().allowAll().build();
```

2021-06-17 15:27 UTC, andreakreichgauer commented on src/main/java/ca/uhn/fhir/jpa/starter/dotBase/interceptors/UserAuthorizationInterceptor.java
> +  private static final List<IAuthRule> ADMIN_RULES = new RuleBuilder().allowAll().build();
I would suggest to add RESTRICTED_ENDPOINTS as a variable here in order to make it easier to extend it and shorten the RuleBuilder initialization

2021-06-17 15:28 UTC, andreakreichgauer commented on src/main/java/ca/uhn/fhir/jpa/starter/dotBase/interceptors/UserAuthorizationInterceptor.java
> +    .build();
In addition to above: You can iterate over RESCTRICTED ENDPOINTS then and extract it to a separate method.

2021-06-17 15:29 UTC, andreakreichgauer commented on src/main/java/ca/uhn/fhir/jpa/starter/dotBase/interceptors/UserAuthorizationInterceptor.java
> +    return theRequestDetails.getAttribute("_username").toString();
there should be a check for `theRequestDetails.getAttribute("_username")==null` here to avoid NullPointerExceptions

2021-06-17 15:30 UTC, andreakreichgauer reviewed
Nice! Just some small refactorings

2021-06-17 21:17 UTC, defo10 commented on src/main/java/ca/uhn/fhir/jpa/starter/dotBase/interceptors/UserAuthorizationInterceptor.java
> +    .build();
very sleek one!

2021-06-21 09:16 UTC, andreakreichgauer commented on src/main/java/ca/uhn/fhir/jpa/starter/dotBase/interceptors/UserAuthorizationInterceptor.java
> +    );
This won't work in production environment. If you want to log this here, declare this one instead:
```  
private static final org.slf4j.Logger ourLog = org.slf4j.LoggerFactory.getLogger(UserAuthorizationInterceptor.class) 
``` 
and then 
```suggestion
    if (adminUserName == null || adminUserName.equals("")) 
      ourLog.warn("Missing property admin username.");
```

2021-06-21 13:00 UTC, andreakreichgauer approved these changes
Nice :+1:

2021-06-21 19:54 UTC, merged